controllers/ShopController.php
<?php

namespace app\controllers;

use app\models\ProductCategory;
use app\models\Product;
use app\models\Cart;
use app\models\Shop;

class ShopController extends \yii\web\Controller
{
	# магазин
    public function actionShop($id=0)
    {
    	return $this->render('shop',['categories' => $this->formatedCategory(),
    								 'products' => Product::findall(['id_product_category'=>$id])
        								]);
    }

    # Корзина
    public function actionCart ()
    {
        $cart = (new Shop())->getCart();
        $products = Product::find()->where(['in', 'id', array_keys($cart)])->all();

        return $this->render('cart', ['products' => $products,
                                      'carts' => $cart]);
    }

    # ajax add cart
    public function actionAddcart ()
    {
    	
    	if(\Yii::$app->request->isAjax){
            $post = \Yii::$app->request->post();
            if (\Yii::$app->user->isGuest) {
                $quantity = Shop::saveCartCookie($post['id']*1);
            } else {
                $quantity = Shop::saveCartDb($post['id']*1);                
            }
    		
    	}
    	return json_encode(['quantity'=>$quantity]);
    }

    protected function formatedCategory()
    {
    	$cat = ProductCategory::find(['active' => 1])->orderBy('parent_id')->all();
    	$new_cat = [];
    	foreach ($cat as $value) {
    		if ($value->parent_id == 0) {
    			$new_cat[] = $value;
    			$this->recursiveCategory($value->id, 1, $cat, $new_cat);
    		}
    	}
    	return $new_cat;
    }

    private function recursiveCategory($id, $count, $mass, &$new_cat)
    {
    	$count++;
    	foreach ($mass as $value) {
    		if ($value->parent_id == $id) {
    			$value->title = str_repeat("&emsp;", $count).$value->title;
    			$new_cat[] = $value;
    			$this->recursiveCategory($value->id, $count, $mass, $new_cat);
    		}
    	}
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\Cart;
use app\helpers\MyUtils;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
     
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'Shop', 'url' => ['/shop/shop']],
        ['label' => 'Cart ('.MyUtils::getCountCart().')',
         'url' => ['/shop/cart'], 
         'linkOptions'=>['id'=>'countProduct']],
    ];
     
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
     
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
        'encodeLabels' =>'false',
    ]);
     
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>